// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZRu-gKPOAOzOoU9pqm0zgT-lOb5QqqIs',
    appId: '1:406230987978:web:8d4cf26dd559bc58c4f033',
    messagingSenderId: '406230987978',
    projectId: 'homescout-4cdfb',
    authDomain: 'homescout-4cdfb.firebaseapp.com',
    storageBucket: 'homescout-4cdfb.firebasestorage.app',
    measurementId: 'G-M1Q8WCW79G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzbN-BFSL1CYpxtZcLulTUWCVURTGSnhE',
    appId: '1:406230987978:android:f6c1964ba6ca000ac4f033',
    messagingSenderId: '406230987978',
    projectId: 'homescout-4cdfb',
    storageBucket: 'homescout-4cdfb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxuaMMNjHI0G9YSYIy-RyjTMsf_ZCzSe8',
    appId: '1:406230987978:ios:d99a9f381ffc74aac4f033',
    messagingSenderId: '406230987978',
    projectId: 'homescout-4cdfb',
    storageBucket: 'homescout-4cdfb.firebasestorage.app',
    iosBundleId: 'com.example.realEstate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxuaMMNjHI0G9YSYIy-RyjTMsf_ZCzSe8',
    appId: '1:406230987978:ios:7e08869fe944f683c4f033',
    messagingSenderId: '406230987978',
    projectId: 'homescout-4cdfb',
    storageBucket: 'homescout-4cdfb.firebasestorage.app',
    iosBundleId: 'com.example.realEstate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZRu-gKPOAOzOoU9pqm0zgT-lOb5QqqIs',
    appId: '1:406230987978:web:c2d3f4206e86b961c4f033',
    messagingSenderId: '406230987978',
    projectId: 'homescout-4cdfb',
    authDomain: 'homescout-4cdfb.firebaseapp.com',
    storageBucket: 'homescout-4cdfb.firebasestorage.app',
    measurementId: 'G-QXD3L09QPT',
  );
}